"""add must_change_password to users

Revision ID: 94c732d3327c
Revises: 1f8909aa7a1b
Create Date: 2026-09-06 22:28:31.098630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c732d3327c'
down_revision: Union[str, Sequence[str], None] = '1f8909aa7a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # FIX: autogenerate left this as NOT NULL with no default. That's fine
    # against an empty table, but this project's users table already has
    # rows -- ADD COLUMN ... NOT NULL with nothing to backfill existing
    # rows would fail outright. server_default backfills every existing
    # row with False before the NOT NULL constraint is enforced.
    op.add_column(
        'users',
        sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
